### ISSUE TITLE
disk meta record cleanup has no effect on old bloom filter data

### ISSUE THREAD

**Issue by dyusupov** [Nexenta/edgefs#313]
### Summary 

Disk meta record cleanup has no effect on old bloom filter data.
As a result, old keys get loaded, which makes bloom filter less efficient

### Steps to reproduce the behavior

wipefs + dd of disk, restart daemon

### Expected behavior

Should not use any of the old data.

### Actual behavior

Jul 22 19:01:25.569 rook-edgefs-target-0 ccowd[46509] notice  [6503]  reptrans-rd.c:10598 : Dev(scsi-35000cca270172e68) mdcache for parthas been re-created
Jul 22 19:01:25.588 rook-edgefs-target-0 ccowd[46509] notice  [6503]  reptrans-rd.c:10693 : Dev(scsi-35000cca270172e68) part 1: needed to take bloom load slow path
Jul 22 19:01:25.588 rook-edgefs-target-0 ccowd[46509] notice  [6503]  reptrans-rd.c:10693 : Dev(scsi-35000cca270172e68) part 2: needed to take bloom load slow path
Jul 22 19:01:25.589 rook-edgefs-target-0 ccowd[46509] notice  [6503]  reptrans-rd.c:10693 : Dev(scsi-35000cca270172e68) part 3: needed to take bloom load slow path
Jul 22 19:01:25.590 rook-edgefs-target-0 ccowd[46509] notice  [6503]  reptrans-rd.c:10693 : Dev(scsi-35000cca270172e68) part 4: needed to take bloom load slow path
Jul 22 19:01:25.591 rook-edgefs-target-0 ccowd[46509] notice  [6503]  reptrans-rd.c:10693 : Dev(scsi-35000cca270172e68) part 5: needed to take bloom load slow path
Jul 22 19:01:25.592 rook-edgefs-target-0 ccowd[46509] notice  [6503]  reptrans-rd.c:10693 : Dev(scsi-35000cca270172e68) part 6: needed to take bloom load slow path
Jul 22 19:01:25.592 rook-edgefs-target-0 ccowd[46509] notice  [6503]  reptrans-rd.c:10693 : Dev(scsi-35000cca270172e68) part 7: needed to take bloom load slow path
Jul 22 19:01:25.592 rook-edgefs-target-0 ccowd[46509] notice  [6503]  reptrans-rd.c:10693 : Dev(scsi-35000cca270172e68) part 8: needed to take bloom load slow path
Jul 22 19:01:25.610 rook-edgefs-target-0 ccowd[46509] notice  [10063]  reptrans-rd.c:994  : Dev(scsi-35000cca270172e68/07): loaded 157963 bloom filter keys (took ~ 16 ms), err: 0
Jul 22 19:01:25.611 rook-edgefs-target-0 ccowd[46509] notice  [10057]  reptrans-rd.c:994  : Dev(scsi-35000cca270172e68/01): loaded 157963 bloom filter keys (took ~ 21 ms), err: 0
Jul 22 19:01:25.612 rook-edgefs-target-0 ccowd[46509] notice  [10058]  reptrans-rd.c:994  : Dev(scsi-35000cca270172e68/02): loaded 157963 bloom filter keys (took ~ 22 ms), err: 0
Jul 22 19:01:25.614 rook-edgefs-target-0 ccowd[46509] notice  [10059]  reptrans-rd.c:994  : Dev(scsi-35000cca270172e68/03): loaded 157963 bloom filter keys (took ~ 22 ms), err: 0
Jul 22 19:01:25.615 rook-edgefs-target-0 ccowd[46509] notice  [10062]  reptrans-rd.c:994  : Dev(scsi-35000cca270172e68/06): loaded 157963 bloom filter keys (took ~ 22 ms), err: 0
Jul 22 19:01:25.616 rook-edgefs-target-0 ccowd[46509] notice  [10056]  reptrans-rd.c:994  : Dev(scsi-35000cca270172e68/00): loaded 157963 bloom filter keys (took ~ 27 ms), err: 0
Jul 22 19:01:25.616 rook-edgefs-target-0 ccowd[46509] notice  [10061]  reptrans-rd.c:994  : Dev(scsi-35000cca270172e68/05): loaded 157963 bloom filter keys (took ~ 23 ms), err: 0
Jul 22 19:01:25.617 rook-edgefs-target-0 ccowd[46509] notice  [10060]  reptrans-rd.c:994  : Dev(scsi-35000cca270172e68/04): loaded 157963 bloom filter keys (took ~ 24 ms), err: 0

### EdgeFS version

1.2.25

Earlier versions also likely affected.

### Deployment type

- [x] Kubernetes with Rook Operator
- [x] Docker Compose

- [x] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [x] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other
